//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace external.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMobile
    {
        public int ID_PK { get; set; }
        public string m_name { get; set; }
        public string m_brand { get; set; }
        public decimal m_discount { get; set; }
        public decimal m_price { get; set; }
    }
}
