//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace external.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUser
    {
        public int ID_PK { get; set; }
        public string u_name { get; set; }
        public int u_psw { get; set; }
    }
}
